mod cli;
mod config;
mod discovery;
mod router;
mod schema;

use std::path::PathBuf;

use clap::{CommandFactory, Parser};
use clap_complete::{Shell, generate};
use cli::{Cli, Command};

fn main() {
    let cli = Cli::parse();

    if let Some(shell) = cli.setup_completions {
        if let Err(e) = setup_completions(shell, cli.config.as_deref()) {
            eprintln!("attach-meta: {e}");
            std::process::exit(1);
        }
        return;
    }

    let command = cli.command.unwrap_or_else(|| {
        eprintln!("attach-meta: no command provided — try --help");
        std::process::exit(1);
    });

    if let Command::Completions { shell } = command {
        generate(
            shell,
            &mut Cli::command(),
            "attach-meta",
            &mut std::io::stdout(),
        );
        return;
    }

    if let Command::Schema = command {
        print_schema(cli.json);
        return;
    }

    if let Command::DoubleComplete {
        current_word_index,
        words,
    } = command
    {
        let config = config::load_config(cli.config.clone()).unwrap_or_default();
        router::run_double_complete(
            current_word_index,
            &words,
            cli.tool,
            config,
            cli.verbose,
        );
        return;
    }

    let config = config::load_config(cli.config.clone()).unwrap_or_else(|e| {
        eprintln!("attach-meta: config error: {e}");
        std::process::exit(1);
    });
    if let Err(e) = router::dispatch(command, cli.tool, cli.workfile, cli.json, config) {
        eprintln!("attach-meta: {e}");
        std::process::exit(1);
    }
}

fn print_schema(json: bool) {
    use schema::DiscoveryKey;
    let version = env!("CARGO_PKG_VERSION");
    if json {
        // Skeleton discovery JSON a tool author can copy and fill in.
        println!("{{");
        println!("  \"protocol_version\": \"{version}\",");
        println!("  \"tool_name\": \"<your-tool-name>\",");
        println!("  \"tool_version\": \"<your-tool-version>\",");
        println!("  \"commands\": {{");
        let all = DiscoveryKey::ALL;
        for (i, dk) in all.iter().enumerate() {
            let spec = dk.spec();
            let argv_json: String = spec.argv.iter()
                .map(|s| format!("\"{s}\""))
                .collect::<Vec<_>>()
                .join(", ");
            let comma = if i < all.len() - 1 { "," } else { "" };
            println!(
                "    \"{}\": {{ \"argv\": [{argv_json}], \"supported\": true }}{comma}",
                spec.key
            );
        }
        println!("  }}");
        println!("}}");
    } else {
        println!("attach-meta protocol {version} — expected discovery commands\n");
        let key_width = DiscoveryKey::ALL.iter().map(|dk| dk.spec().key.len()).max().unwrap_or(0);
        for dk in DiscoveryKey::ALL {
            let spec = dk.spec();
            let argv = spec.argv.join(" ");
            println!("  {:<key_width$}  argv: [{argv}]", spec.key);
            println!("  {:<key_width$}  {}", "", spec.description);
            println!();
        }
    }
}

fn setup_completions(shell: Shell, config_path: Option<&std::path::Path>) -> anyhow::Result<()> {
    let path = completion_path(shell)?;

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let content = match shell {
        Shell::Zsh => generate_zsh_script(config_path),
        Shell::Bash => generate_bash_script(config_path),
        Shell::Fish => generate_fish_script(config_path),
        _ => {
            let mut buf = Vec::new();
            generate(shell, &mut Cli::command(), "attach-meta", &mut buf);
            String::from_utf8(buf)?
        }
    };

    std::fs::write(&path, content)?;
    println!("Installed {} completions to {}", shell, path.display());
    maybe_print_hint(shell, &path);

    Ok(())
}

/// Single-quote a string for safe shell interpolation.
fn shell_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

fn config_arg(config_path: Option<&std::path::Path>) -> String {
    config_path
        .map(|p| format!(" --config {}", shell_quote(&p.to_string_lossy())))
        .unwrap_or_default()
}

fn generate_zsh_script(config_path: Option<&std::path::Path>) -> String {
    let cfg = config_arg(config_path);
    format!(
        r#"#compdef attach-meta
# Generated by attach-meta --setup-completions zsh

_attach-meta() {{
    local -a completions vals descs
    completions=("${{(@f)$(attach-meta{cfg} __complete \
        --current-word-index $((CURRENT - 1)) \
        -- "${{words[@]}}" 2>/dev/null)}}")
    for line in $completions; do
        vals+=("${{line%%$'\t'*}}")
        if [[ "$line" == *$'\t'* ]]; then
            descs+=("${{line#*$'\t'}}")
        else
            descs+=('')
        fi
    done
    _describe 'completions' vals descs
}}

compdef _attach-meta attach-meta
"#
    )
}

fn generate_bash_script(config_path: Option<&std::path::Path>) -> String {
    let cfg = config_arg(config_path);
    format!(
        r#"# Generated by attach-meta --setup-completions bash
_attach_meta_completions() {{
    local IFS=$'\n'
    local completions
    completions=$(attach-meta{cfg} __complete \
        --current-word-index "$COMP_CWORD" \
        -- "${{COMP_WORDS[@]}}" 2>/dev/null) || return
    [ -z "$completions" ] && return
    while IFS=$'\t' read -r value _desc; do
        COMPREPLY+=("$value")
    done <<< "$completions"
}}
complete -F _attach_meta_completions attach-meta
"#
    )
}

fn generate_fish_script(config_path: Option<&std::path::Path>) -> String {
    let cfg = config_arg(config_path);
    format!(
        r#"# Generated by attach-meta --setup-completions fish
function __attach_meta_completions
    set -l words (commandline -opc)
    set -l wcount (count $words)
    test $wcount -eq 0; and return
    set -l index (math $wcount - 1)
    attach-meta{cfg} __complete --current-word-index $index \
        -- $words 2>/dev/null
end
complete -c attach-meta -f -a "(__attach_meta_completions)"
"#
    )
}

fn completion_path(shell: Shell) -> anyhow::Result<PathBuf> {
    let home =
        dirs::home_dir().ok_or_else(|| anyhow::anyhow!("could not determine home directory"))?;

    let path = match shell {
        Shell::Bash => home.join(".local/share/bash-completion/completions/attach-meta"),
        Shell::Zsh => home.join(".zsh/completions/_attach-meta"),
        Shell::Fish => dirs::config_dir()
            .unwrap_or_else(|| home.join(".config"))
            .join("fish/completions/attach-meta.fish"),
        Shell::Elvish => dirs::config_dir()
            .unwrap_or_else(|| home.join(".config"))
            .join("elvish/lib/attach-meta.elv"),
        Shell::PowerShell => dirs::document_dir()
            .unwrap_or_else(|| home.join("Documents"))
            .join("PowerShell/Completions/attach-meta.ps1"),
        _ => anyhow::bail!("unsupported shell: {shell}"),
    };

    Ok(path)
}

fn maybe_print_hint(shell: Shell, path: &PathBuf) {
    match shell {
        Shell::Zsh => {
            let dir = path.parent().unwrap().display().to_string();
            println!("Hint: ensure {dir} is in your fpath before compinit, e.g.:");
            println!("  fpath=({dir} $fpath)");
            println!("  autoload -Uz compinit && compinit");
        }
        Shell::Bash => {
            println!("Hint: restart your shell or run: source {}", path.display());
        }
        _ => {}
    }
}
